# Generated by Django 5.1.3 on 2025-01-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4, null=True)),
                ('rated', models.CharField(max_length=10, null=True)),
                ('released', models.DateField(null=True)),
                ('runtime', models.CharField(max_length=50, null=True)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('director', models.CharField(max_length=255, null=True)),
                ('writer', models.CharField(max_length=255, null=True)),
                ('actors', models.TextField(null=True)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('awards', models.CharField(max_length=255, null=True)),
                ('poster', models.URLField(null=True)),
                ('metascore', models.IntegerField(null=True)),
                ('imdb_rating', models.FloatField(null=True)),
                ('imdb_votes', models.CharField(max_length=20, null=True)),
                ('imdb_id', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('response', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=18)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course', models.CharField(choices=[('Python', 'Python'), ('AI', 'AI'), ('Java', 'Java')], max_length=20)),
            ],
        ),
    ]
